/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsRetirementRouteImport } from './routes/tools/retirement'
import { Route as ToolsFinancialPlanRouteImport } from './routes/tools/financial-plan'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRetirementRoute = ToolsRetirementRouteImport.update({
  id: '/tools/retirement',
  path: '/tools/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFinancialPlanRoute = ToolsFinancialPlanRouteImport.update({
  id: '/tools/financial-plan',
  path: '/tools/financial-plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enterprise': typeof EnterpriseRoute
  '/financial': typeof FinancialRoute
  '/reviews': typeof ReviewsRoute
  '/tools/financial-plan': typeof ToolsFinancialPlanRoute
  '/tools/retirement': typeof ToolsRetirementRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enterprise': typeof EnterpriseRoute
  '/financial': typeof FinancialRoute
  '/reviews': typeof ReviewsRoute
  '/tools/financial-plan': typeof ToolsFinancialPlanRoute
  '/tools/retirement': typeof ToolsRetirementRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enterprise': typeof EnterpriseRoute
  '/financial': typeof FinancialRoute
  '/reviews': typeof ReviewsRoute
  '/tools/financial-plan': typeof ToolsFinancialPlanRoute
  '/tools/retirement': typeof ToolsRetirementRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/enterprise'
    | '/financial'
    | '/reviews'
    | '/tools/financial-plan'
    | '/tools/retirement'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/enterprise'
    | '/financial'
    | '/reviews'
    | '/tools/financial-plan'
    | '/tools/retirement'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/enterprise'
    | '/financial'
    | '/reviews'
    | '/tools/financial-plan'
    | '/tools/retirement'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FinancialRoute: typeof FinancialRoute
  ReviewsRoute: typeof ReviewsRoute
  ToolsFinancialPlanRoute: typeof ToolsFinancialPlanRoute
  ToolsRetirementRoute: typeof ToolsRetirementRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/retirement': {
      id: '/tools/retirement'
      path: '/tools/retirement'
      fullPath: '/tools/retirement'
      preLoaderRoute: typeof ToolsRetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/financial-plan': {
      id: '/tools/financial-plan'
      path: '/tools/financial-plan'
      fullPath: '/tools/financial-plan'
      preLoaderRoute: typeof ToolsFinancialPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EnterpriseRoute: EnterpriseRoute,
  FinancialRoute: FinancialRoute,
  ReviewsRoute: ReviewsRoute,
  ToolsFinancialPlanRoute: ToolsFinancialPlanRoute,
  ToolsRetirementRoute: ToolsRetirementRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
